# Swiss Army Knife Templates
sak_sys_templates: !include ../www/community/swiss-army-knife-card/sak_templates.yaml

# The user templates are created by the user
sak_user_templates: !include ../lovelace/sak_templates/sak_templates.yaml

# templates pour tuiles
# button_card_templates: !include_dir_merge_named templates/
   
# Mon tableau de bord.

title: Mon Tableau

# Menu de gauche.

sidebar:
  width:
    mobile: 1
    desktop: 25
  hideTopMenu: true
  showTopMenuOnMobile: true
  digitalClock: true
  date: true
  dateFormat: dddd DD MMMM
  style: |
    :host {
        --sidebar-background: #000D29;
        --sidebar-text-color: #BDC1C6;
        --face-color: #00F031;
        --face-border-color: #FFF;
        --sidebar-selected-text-color: rgb(3, 169, 244);
        --sidebar-selected-icon-color: rgb(3, 169, 244);
        background-image: linear-gradient(115051deg, #000000, #151515, #1C1C1C, #2E2E2E, #424242, #585858);
    }
    .sidebarMenu li.active {
        background-color: #2C2E30!important;
        border-radius: 40px!important;
        font-weight: bold!important;
     }
    .sidebarMenu li {
        line-height: 11px!important;
        font-weight: 400!important;
     }
    .bottom {
        width: 100% !important;
        color: #585858!important;
    }
    .digitalClock {0
        color: rgba(255, 255, 255, 0.7)!important;
        font-size: 5.41vw!important;
        font-weight: 500!important;
        letter-spacing: -0.05vw!important;
        text-align: center;
    }
    .date {
        color: rgba(255, 255, 255, 0.7)!important;
        font-size: 2.00vw!important;
        font-weight: 400!important;
        letter-spacing: -0.05vw!important;
        text-align: center;
    }
    .template {
        text-align: center;
        font-weight: 500!important;
    }
     
  sidebarMenu:
  
    - action: navigate
      navigation_path: "vue-page-Information"
      icon: ios:retour-maison#fullcolor # ios:informations#fullcolor
      active: true
      name: Infomations

    - action: navigate
      navigation_path: "vue-page-calendriers"
      icon: ios:calendrier#fullcolor
      active: true
      name: Calendriers

    - action: navigate
      navigation_path: "vue-page-hydro-quebec"
      icon: ios:hydro-quebec#fullcolor
      active: true
      name: Hydro-Québec

    - action: navigate
      navigation_path: "vue-page-meteos"
      icon: ios:meteo#fullcolor 
      active: true
      name: Météo

    - action: navigate
      navigation_path: "vue-page-formule-un"
      icon: ios:f1-voiture-orange#fullcolor
      active: true
      name: Formule Un

    - action: navigate
      navigation_path: "vue-page-systeme"
      icon: ios:ordinateur#fullcolor
      active: true
      name: Infos Système

    - action: navigate
      navigation_path: "vue-page-suivi"
      icon: ios:suivi#fullcolor
      active: true
      name: Suivi

    - action: navigate
      navigation_path: "vue-page-piles"
      icon: ios:pile#fullcolor
      active: true
      name: Piles

    - action: navigate
      navigation_path: "vue-page-medias"
      icon: ios:medias#fullcolor
      active: true
      name: Médias
      
#    - action: navigate
#      navigation_path: "vue-page-tests"
#      icon: mdi:test-tube
#      active: true
#      name: Tests
      
  bottomCard:
    type: horizontal-stack
    cardOptions:
      cards:
        - !include Cartes/Carte-Agenda.yaml
    cardStyle: |
      :host {
        width: 100%;
      }

  template: >
    <li>
      {% if now().hour  < 6 %} 🌙 Bonne nuit {{user}}! 
      {% elif now().hour < 12 %} 🌞 Bon matin {{user}}! 
      {% elif now().hour < 18 %} 😎 Bon après-midi {{user}}! 
      {% else %} 🌜 Bonne soirée {{user}}! {% endif %}
    </li>
    <li>
     {% if states('sensor.nombre_de_lumieres_allumees') < '2' %}
       💡 {{ states('sensor.nombre_de_lumieres_allumees') }} Lumière allumée
     {% else %}
       💡💡 {{ states('sensor.nombre_de_lumieres_allumees') }} Lumières allumées
     {% endif %}
    </li>
    
views:
  # Vue Test
#  - !include Vues/B-Vue-Test.yaml

  # Vue pages

  - !include Vues/Vue-Informations.yaml
  - !include Vues/Vue-Calendriers.yaml
  - !include Vues/Vue-Hydro-Quebec.yaml
  - !include Vues/Vue-Meteo.yaml
  - !include Vues/Vue-Formule-Un.yaml
  - !include Vues/Vue-Systeme.yaml
  - !include Vues/Vue-Suivi.yaml
  - !include Vues/Vue-Piles.yaml
  - !include Vues/Vue-Medias.yaml

  # Sous Vue pièces

  - !include Sous-Vues/Sous-Vue-Piece-Salon.yaml
  - !include Sous-Vues/Sous-Vue-Piece-Cuisine.yaml
  - !include Sous-Vues/Sous-Vue-Piece-Salle-A-Manger.yaml
  - !include Sous-Vues/Sous-Vue-Piece-Salle-Deau.yaml

  - !include Sous-Vues/Sous-Vue-Piece-Bureau.yaml
  - !include Sous-Vues/Sous-Vue-Piece-Chambre-Maitres.yaml
  - !include Sous-Vues/Sous-Vue-Piece-Salle-De-Bain-Maitres.yaml
  - !include Sous-Vues/Sous-Vue-Piece-Salle-De-Repos.yaml

  - !include Sous-Vues/Sous-Vue-Piece-Salle-Familiale.yaml
  - !include Sous-Vues/Sous-Vue-Piece-Chambre-Invites.yaml
  - !include Sous-Vues/Sous-Vue-Piece-Atelier.yaml

  - !include Sous-Vues/Sous-Vue-Piece-exterieur.yaml
