# pop-Up Automations

type: custom:vertical-stack-in-card
card_mod:
    style: |
     ha-card {
      box-shadow: 0 0 0 1px gray;
     }
cards:
  - type: custom:scheduler-card
    include:
      - vacuum
      - group
      - switch
      - light
      - alarm_control_panel
      - scene
      - climate
