# pop-Up Automations

type: custom:vertical-stack-in-card
cards:
  - type: custom:scheduler-card
    include:
      - vacuum
      - group
      - switch
      - light
      - alarm_control_panel
      - scene
      - climate
