sensor:
 - platform: rest
   ssl_cipher_list: intermediate
   resource: "https://www.hydroquebec.com/data/documents-donnees/donnees-ouvertes/json/demande.json"
   name: Demande Electricite Hydro
   device_class: power
   state_class: measurement
   unique_id: edbb1dd6-6160-4279-a64d-1a2b3c
   json_attributes:
   unit_of_measurement: KW 
   value_template: >
     {% set index =  value_json.indexDonneePlusRecent %}
     {{ value_json.details[index]["valeurs"]["demandeTotal"] }}

rest:
  - resource: "https://www.hydroquebec.com/data/documents-donnees/donnees-ouvertes/json/production.json"
    ssl_cipher_list: intermediate
    scan_interval: 3600 
    sensor:
      - name: "Electricite production total"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.total }}'
        device_class: power
        unit_of_measurement: "KW"
        unique_id: 'hydro_quebec_production_total'
      - name: "Electricite production hydraulique"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.hydraulique }}'
        device_class: power
        unit_of_measurement: "KW"
        unique_id: 'hydro_quebec_production_hydraulique'
      - name: "Electricite production éolien"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.eolien }}'
        device_class: power
        unit_of_measurement: "KW"
        unique_id: 'hydro_quebec_production_eolien'
      - name: "Electricite production autres"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.autres }}'
        device_class: power
        unit_of_measurement: "KW"
        unique_id: 'hydro_quebec_production_autres'
      - name: "Electricite production solaire"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.solaire }}'
        device_class: power
        unit_of_measurement: "KW"
        unique_id: 'hydro_quebec_production_solaire'
#      - name: "Electricite production thermique"
#        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.thermique }}'
#        device_class: power
#        unit_of_measurement: "KW"
#        unique_id: 'hydro_quebec_production_thermique'