# États des caméras pour les tuiles de pièces. 
sensor:
    
  - platform: template
    sensors:
      ajout_etat_camera_allee:
        unique_id: "ajout_etat_camera_allee"
        friendly_name: "État de la caméra allée"
        value_template:  >
          {% if is_state('binary_sensor.blink_allee_camera_armed', 'on') %} 
            OK                      
          {% else %}
            PASOK
          {% endif %}         
          
  - platform: template
    sensors:
      ajout_etat_camera_cuisine:
        unique_id: "ajout_etat_camera_cuisine"
        friendly_name: "État de la caméra cuisine"
        value_template:  >
          {% if is_state('binary_sensor.blink_cuisine_camera_armed', 'on') %} 
            OK                      
          {% else %}
            PASOK
          {% endif %}         
          
  - platform: template
    sensors:
      ajout_etat_camera_galerie_arriere:
        unique_id: "ajout_etat_camera_galerie_arriere"
        friendly_name: "État de la caméra galerie arrière"
        value_template:  >
          {% if is_state('binary_sensor.blink_galerie_arriere_camera_armed', 'on') %} 
            OK                      
          {% else %}
            PASOK
          {% endif %}         
          
  - platform: template
    sensors:
      ajout_etat_camera_galerie_avant:
        unique_id: "ajout_etat_camera_galerie_avant"
        friendly_name: "État de la caméra galerie avant"
        value_template:  >
          {% if is_state('binary_sensor.blink_galerie_avant_camera_armed', 'on') %} 
            OK                      
          {% else %}
            PASOK
          {% endif %}         
          
  - platform: template
    sensors:
      ajout_etat_camera_sous_sol:
        unique_id: "ajout_etat_camera_sous_sol"
        friendly_name: "État de la caméra sous-sol"
        value_template:  >
          {% if is_state('binary_sensor.blink_sous_sol_camera_armed', 'on') %} 
            OK                      
          {% else %}
            PASOK
          {% endif %}         
          
  - platform: template
    sensors:
      ajout_etat_camera_salon:
        unique_id: "ajout_etat_camera_salon"
        friendly_name: "État de la caméra salon"
        value_template:  >
          {% if is_state('binary_sensor.blink_salon_camera_armed', 'on') %} 
            OK                      
          {% else %}
            PASOK
          {% endif %}         
        
